version: 1.0.{build}

skip_tags: true

branches:
  only:
  - coding-pages

image: Ubuntu1804

environment:
  CODING_TOKEN:
    secure: MnYloU4sOET9OWZg4MjYyJCFbEY5C6tN/ltAAcJEKU6krCNDACheYm4QThCKKBWo

build_script:
- sh: >-

    cd /home/appveyor/projects/gms2-help
    
    git init
    
    git config --global user.name "deciia"
    
    git config --global user.email "deciia@qq.com"
    
    git add .
    
    git commit -m "Sync By AppVeyor"
    
    git push --force --quiet "https://deciia:%CODING_TOKEN%@git.coding.net/deciia/GMS2_help.git" coding-pages:coding-pages
