name: Mirror from Gitee

on:
  #push:
  #  branches: [ master ]
  #schedule:
  #  - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Clone repo
        uses: Yikun/hub-mirror-action@master
        with:
          src: gitee/GamemakerChina
          dst: github/GamemakerChina
          dst_key: ${{ secrets.GITHUB_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITHUB_TOKEN }}
          static_list: "GMS2_manual_en2ch"
